### ISSUE TITLE
Vercel Serverless Function Memory Limit

### ISSUE THREAD

**Issue by Siva2406** [jeetiss/vercel-canvas#1]
We followed the method suggested by you, but it did not help. Still, we are facing the same issue. We have opened a separate thread under the Vercel NextJS repo - https://github.com/vercel/next.js/discussions/40248

 Any assistance you can provide would be greatly appreciated.

**Comment by jeetiss** [comment]
Try to use https://github.com/Brooooooklyn/canvas, it works with vercel from the box but has some glitches when I tested it the last time half a year ago.
